# ---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: maven-hello-app
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production

# ---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/ascendant-voice-398405/locations/asia-northeast1/clusters/staging

# ---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/ascendant-voice-398405/locations/asia-northeast1/clusters/production
