apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-hello-app

spec:
  selector:
    matchLabels:
      app: maven-hello-app
  template:
    metadata:
      labels:
        app: maven-hello-app
    spec:
      containers:
      - name: maven-hello-app
        image: asia-northeast1-docker.pkg.dev/ascendant-voice-398405/maven-repo/hellospring:latest
        ports:
          - containerPort: 8080
